# .github/workflows/daily-commits.yml
name: Daily Commits

on:
  schedule:
    # This schedule runs daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Run daily commits script
        run: |
          python main.py
